### ISSUE TITLE
0.7.4 fails when unable to find defaultConfig module, changing back to 0.7.3 fixes it

### ISSUE THREAD

**Issue by brandonpittman** [tailwindcss/tailwindcss#628]
After upgrading to 0.7.4, got a string of nasty errors about not being able to find module `tailwindcss/defaultConfig`.

```sh
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Cannot find module 'tailwindcss/defaultConfig'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/brandonpittman/Sites/g-blog/tailwind.js:27:21)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at getConfig (/Users/brandonpittman/Sites/g-blog/node_modules/gridsome-plugin-tailwindcss/node_modules/tailwindcss/lib/index.js:49:96)
    at /Users/brandonpittman/Sites/g-blog/node_modules/gridsome-plugin-tailwindcss/node_modules/tailwindcss/lib/processTailwindFeatures.js:9:20
    at LazyResult.run (/Users/brandonpittman/Sites/g-blog/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/Users/brandonpittman/Sites/g-blog/node_modules/postcss/lib/lazy-result.js:208:26)
    at runLoaders (/Users/brandonpittman/Sites/g-blog/node_modules/webpack/lib/NormalModule.js:301:20)
    at /Users/brandonpittman/Sites/g-blog/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/brandonpittman/Sites/g-blog/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/brandonpittman/Sites/g-blog/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Promise.resolve.then.then.catch (/Users/brandonpittman/Sites/g-blog/node_modules/postcss-loader/src/index.js:208:9)
 @ ./src/main.js 10:0-43
 @ ./node_modules/gridsome/app/app.js
 @ ./node_modules/gridsome/app/entry.client.js
 @ multi ./node_modules/gridsome/app/entry.client.js
```
